### ISSUE TITLE
AssertionError: Checkpoint model/keypoint_rcnn_R_101_FPN_3x.pkl not found!

### ISSUE THREAD

**Issue by lantingyue11** [iTomstudio/predictor_situp#1]
Hi can  you tell me the question?

**Comment by iTomstudio** [comment]
你好，可以参照 https://github.com/facebookresearch/detectron2/blob/master/GETTING_STARTED.md 的demo，将官方demo的--config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml  修改为运行 --config-file ../configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml ，detectron2 可以自行下载预训练模型

**Comment by chenhao-1115** [comment]
更改setup_cfg函数，增加cfg.MODEL.WEIGHTS，即可自动下载pkl，具体对应关系看这里：https://github.com/facebookresearch/detectron2/blob/master/detectron2/model_zoo/model_zoo.py
----------------------------------------------------------------------------------------------
def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_file("./model/keypoint_rcnn_R_101_FPN_3x.yaml")
    cfg.MODEL.WEIGHTS = "detectron2://COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x/138363331/model_final_997cc7.pkl"
    cfg.merge_from_list(args.opts)
    # Set score_threshold for builtin models
    cfg.MODEL.RETINANET.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = args.confidence_threshold
    cfg.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = args.confidence_threshold
    cfg.freeze()
    return cfg

**Comment by lantingyue11** [comment]
thank&nbsp; you



---Original---

**Comment by iTomstudio** [comment]
链接: https://pan.baidu.com/s/1CIjF-GHqCk6FGW-ABxEzYA 提取码: d5uf   （建议）
或者联系QQ 1443183133 索取
