### ISSUE TITLE
改成摄像头输入应该怎么改

### ISSUE THREAD

**Issue by wzyxdwll** [iTomstudio/predictor_situp#2]
你好，我看了下代码，我现在想将摄像头作为输入源不知道如何下手，可否指导一下
或者给个实例demo

现在摄像头作为输入源我已经做好了，但是您的代码里面是视频作为输入源，然后读出帧率与帧数逐帧处理
关键部分是
```
for  ordinal_num, resulte_dictionary in enumerate(tqdm.tqdm(demo.run_on_video(video,calculate_dictionary), total=num_frames)):
```
但是我不知道run_on_video这个函数的作用是什么以及返回结果是什么

非常感谢

**Comment by iTomstudio** [comment]
参照这个地址，先跑一下detectron 的demo，https://github.com/facebookresearch/detectron2/blob/master/demo/demo.py
然后我觉得你就应该能明白怎么改了，思路把你贴的那一行中的video，替换为 cv2.VideoCapture(0)，具体怎么改参照链接

**Comment by iTomstudio** [comment]
参照这个地址，先跑一下detectron 的demo，https://github.com/facebookresearch/detectron2/blob/master/demo/demo.py
然后我觉得你就应该能明白怎么改了，思路把你贴的那一行中的video，替换为 cv2.VideoCapture(0)，具体怎么改产找链接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iTomstudio/predictor_situp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 下午5:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[iTomstudio/predictor_situp] 改成摄像头输入应该怎么改 (#2)





 
你好，我看了下代码，我现在想将摄像头作为输入源不知道如何下手，可否指导一下
 或者给个实例demo
 
非常感谢
